### ISSUE TITLE
loss: nan

### ISSUE THREAD

**Issue by RingoTC** [spdj2271/DeepKmeans#1]
下载数据集后，得到
loss: nan 的结果
![image](https://user-images.githubusercontent.com/6525061/156528351-b67324f8-7068-4131-b60a-5bdfea8819dc.png)
请问是还需要什么其他的配置或者修改吗？

**Comment by spdj2271** [comment]
感觉您的关注。
我在一个全新的环境下，重新测试了该项目。并未出现loss=nan的情况。
![图片](https://user-images.githubusercontent.com/30624620/156536448-4e70a473-2e50-482b-9bfd-833860b758b0.png)

**Comment by RingoTC** [comment]
感谢您的及时回复，可以问一下您的 nvidia-driver 和 cudnn 等版本号吗？

**Comment by spdj2271** [comment]
Driver Version: 495.44       CUDA Version: 11.5
![图片](https://user-images.githubusercontent.com/30624620/156701676-046160e5-1de1-4981-83fa-f68d7f505836.png)

**Comment by Zuowei-Wang** [comment]
感谢作者的分享，就是我在windows上运行显示显存不够用，本人4060显卡，8g显存，似乎是window并没有分配全部的显存用于学习，请问作者是在硬件条件下运行的，是否可以告知，方便参考一下
<img width="1232" alt="屏幕截图 2024-03-02 171025" src="https://github.com/spdj2271/DEKM/assets/125523384/fc9115d4-3641-411a-9c3a-7231ba94067b">

**Comment by spdj2271** [comment]
我实验用的GPU是3090TI，显存是24G。 如果你的显存不够，可以小批次计算嵌入矩阵H 。另一个更便捷的做法是用CPU计算H：
```diff
- H = model(x).numpy()[:, :hidden_units] # DEKM.py Line82
+ with tf.device('cpu'):
+    H = model(x).numpy()[:, :hidden_units]
```
