### ISSUE TITLE
DEKM-dense doesn't work for Reuters & RCV1 datasets, gives a shape error in get_acc_nmi function

### ISSUE THREAD

**Issue by joshianirudh** [spdj2271/DeepKmeans#2]

**Comment by spdj2271** [comment]
Thank you for your attention. I rerun the DEKM_dense.py on REUTERS dataset. And no errors occurred. 
![图片](https://user-images.githubusercontent.com/30624620/164418908-1bd14518-fac4-49be-b884-0e70dd574fda.png)

For shape error, you can try to add `.ravel()` to the two lines:
```diff
# utils.py
def get_ACC_NMI(_y, _y_pred):
-    y = np.array(_y)
-    y_pred = np.array(_y_pred)
+    y = np.array(_y).ravel() 
+    y_pred = np.array(_y_pred).ravel() 
```

**Comment by joshianirudh** [comment]
Hey any idea where I can get the text data for the reuters and RCV 1
dataset.
Like the actual dataset.

**Comment by spdj2271** [comment]
[scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_rcv1.html?highlight=rcv1#sklearn.datasets.fetch_rcv1) seems to provide the full  RCV1 dataset (text-wise).

REUTERS I mentioned in my paper refers to the REUTERS-10K dataset in paper [DEC](https://arxiv.org/abs/1511.06335), while RCV1 refers to the dataset in paper [DKM](https://arxiv.org/abs/1806.10069v1). Indeed both  REUTERS-10K and RVC1  here is a subset of original [RCV1](ttps://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_rcv1.html?highlight=rcv1#sklearn.datasets.fetch_rcv1).

**Comment by joshianirudh** [comment]
Hey man thanks alot for ur help, I'm currently working on a research paper
myself, ur paper has been off great help to us.

Ur idea of increasing the dimensions in the  encoder instead of lowering
dimensions, was fascinating.

Also the way u guys approached clustering using K Means.

I was surprised to see that no one has cited your paper, maybe if our
research yield good results and we proceed to publishing. We'll be sure to
cite your work.

Cheers mate

**Comment by spdj2271** [comment]
Good luck

**Comment by corneliusjustin** [comment]
@joshianirudh Hi, I want to do an undergraduate thesis and considering using DEKM for text clustering. How's your work result? May I see it if possible? Thanks!

**Comment by joshianirudh** [comment]
> 

Hey man,
DEKM didn't get me the desired results I wanted.
But there could be several reasons for this:
1)Like Bad word embeddings that aren't representing the text data very well
2) or Kmeans might not be suited to the representation

Any how, I recommend you try out DEKM for your datasets.

Try experimenting with InstructXL and other new transformer embeddings for better results.

You can also try UMAP for dimensionality reduction.

**Comment by adelightday** [comment]
Hi @joshianirudh @corneliusjustin, I'm trying to execute DEKM for my own datasets as well. How's your work result guys? I'm looking for another references since it didn't get me the desired results I wanted. If any, I'd like to see your paper. Thanks!
