### ISSUE TITLE
IndexError: index 4 is out of bounds for axis 0 with size 4 in utils.py

### ISSUE THREAD

**Issue by Shutterbug2109** [spdj2271/DeepKmeans#3]
```
y = np.array(_y)   #original labels
y_pred = np.array(_y_pred) #predicted labels
s = np.unique(y_pred) # s =5 ( As I gave n_clusters= 5 to KMenas after calculating the possible clusters in my data using Elbow method) 
t = np.unique(y) # t = 4 (original clusters in my data i.e. Ground Truth*)
```
<html>
<body>

Getting an error in this step where index is out of bound i.e.  5 > 4
`idx = np.logical_and(y_pred == s[i], y == t[j])`
--

</body>
</html>

Can you please suggest a solution to this limitation ?

**Comment by spdj2271** [comment]
Maybe, you can rewrite Line 16 in utils.py as:
``` diff
# utils.py Line 16
-   N = len(np.unique(y_pred))
+ N = max(len(np.unique(y)),len(np.unique(y_pred)))
```

**Comment by Shutterbug2109** [comment]
@spdj2271  Thank you for your reply. I have tried the change suggested by you. But I am getting the same error. 

I have tried this : 

```
y = np.array(_y)
y_pred = np.array(_y_pred)

y_pred, y = np.array(y_pred).astype(int), np.array(y).astype(int)
assert y_pred.size == y.size
D = max(y_pred.max(), y.max())+1
w = np.zeros((D, D), dtype=np.int64)
for i in range(y_pred.size):
    w[y_pred[i], y[i]] += 1
row, col = linear_assignment(w.max()-w)

acc = sum([w[row[i],col[i]] for i in range(row.shape[0])]) * 1.0 / y_pred.size
```

Can you please let me know if this is correct ? It will be really helpful. Looking forward

**Comment by spdj2271** [comment]
You can input some toy examples to this function for testing.

Also, previous [work](http://proceedings.mlr.press/v48/xieb16.pdf) (section 5.5. Number of Clusters) also relates to your demand. Thier code is available [here](https://github.com/piiswrong/dec/blob/master/dec/dec.py) (Line 57).

**Comment by Shutterbug2109** [comment]
Thank you for your suggestions.
