### ISSUE TITLE
Y = VH vs H_vt

### ISSUE THREAD

**Issue by corneliusjustin** [spdj2271/DeepKmeans#4]
Hi, i have a question regarding the equation Y = VH in the paper and H_vt in the code. So, V's columns are eigenvectors of Sw right, either in the paper or the code. Then, in the paper, H is a e x n matrix, where n is number of data points and e is dimension of embedding space. But you use n x e matrix in the code for H, which means H in the code same as H^T in the paper. But, in the paper, u guys mention Y = VH, however in the code u use H_vt = np.matmul(H, V), where H_vt supposed to be the same as Y. So, if I use the paper notation, isn't the H_vt in the code computes H^T times V? Where I think it is supposed to be Y = VH or Y^T = H^T V^T. So, I don't get why the code use H^T times V, where H^T V = VH is not generally true. Thanks

**Comment by spdj2271** [comment]
Hi! You can observe the correspondence between notations in the paper and those in the code in the following table:
|   Notations in the paper   |   Notations in the code   |
| ---- | ---- |
| $H\in\mathbb{R}^{e\times n}$  (each column is a data point) | $H\in\mathbb{R}^{n\times e}$  (each row is a data point) |
| $V\in\mathbb{R}^{e\times e}$  (each row is an eigenvector) | $V\in\mathbb{R}^{e\times e}$  (each column is an eigenvector) |
| $Y=VH\in\mathbb{R}^{e\times n}$  (each column is a data point) | $H_{vt}=HV\in\mathbb{R}^{n\times e}$ (each row is a data point) |

As shown, all the notations in the code are the transpose of those in the paper. **Note that $V$'s rows represent eigenvectors in the paper, while $V$'s columns represent eigenvectors in the code.** The two instances of $V$ are defined differently. Thus the expression $Y=VH$ in the paper being equivalent to $H_{vt}=HV$ in the code.

**Comment by corneliusjustin** [comment]
Hi, thank you so much for the answer. Can you show me which part in the paper highlights the eigenvectors in the paper is structured as $V$'s rows rather than $V$'s columns? Thanks!

**Comment by spdj2271** [comment]
You can derive the structure of $V$ from Equation 4 or the following statement within the paper: 

> Each row vector of the orthonormal transformation matrix is the eigenvector of the within-class scatter matrix.

**Comment by corneliusjustin** [comment]
ahh i see, thank you so much!
