### ISSUE TITLE
alternative dependencies

### ISSUE THREAD

**Issue by adelightday** [spdj2271/DeepKmeans#6]
Hi, I want to ask if there are alternative dependencies to clone the code locally. I have tried using Python 3.8 and venv but there is still an error for DEKM_dense.py

It stated
"No matching distribution found for tensorflow==2.4.1"

Many thanks for considering my request.

**Comment by spdj2271** [comment]
Hi, I didn't quite understand your question. Are you having trouble configuring the environment for DEKM_dense.py? If so, you can use this Colab [notebook](https://colab.research.google.com/drive/1L2HEDqsB_2ZsT2oxNxXj1GfIC72piTWj?usp=sharing), where I successfully run DEKM_dense.py on the 20NEWS dataset.

**Comment by adelightday** [comment]
Thank you for attaching the Colab notebook! Just wondering, how do I lunch an experiment for DEKM_dense.py? Is it the same with DEKM.py one? python DEKM.py MNIST for MNIST dataset?

**Comment by spdj2271** [comment]
> how do I lunch an experiment for DEKM_dense.py

First, select the dataset you want to use for the experiment by revising this [line](https://colab.research.google.com/drive/1L2HEDqsB_2ZsT2oxNxXj1GfIC72piTWj#scrollTo=ONB35TMZCmoZ&line=151&uniqifier=1): `ds_name = ['REUTERS', '20NEWS', 'RCV1'][1] # for 20NEWS`. Then, run all the notebook cells.

> Is it the same with DEKM.py one?

A little different. In the Colab notebook for DEKM_dense.py, you select the dataset by modifying this [line](https://colab.research.google.com/drive/1L2HEDqsB_2ZsT2oxNxXj1GfIC72piTWj#scrollTo=ONB35TMZCmoZ&line=151&uniqifier=1). In contrast, for DEKM.py, you specify the dataset through command-line arguments `python DEKM.py MNIST` or `python DEKM.py USPS`.

**Comment by adelightday** [comment]
Tysm for the answer!!
