### ISSUE TITLE
unsupervised manner in DEKM

### ISSUE THREAD

**Issue by adelightday** [spdj2271/DeepKmeans#8]
Hello, I'm curious about the unsupervised manner in DEKM. There should not be any label for the dataset, but there are (mostly) feature and target files in your provided datasets. The algorithm also runs with those two files as x and y. Isn't that contradictive with the unsupervised meaning?

I'm looking forward to hearing your reasons. Thanks!

**Comment by spdj2271** [comment]
The labels are used solely for computing clustering performance metrics (ACC and NMI), which is a standard practice in clustering literature.

**Comment by adelightday** [comment]
Oh missed that part, thank you so much!
